#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
dunst &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
# bspc config normal_border_color  #434C5E
# bspc config active_border_color  #5E81AC

bspc config top_padding		57
bspc config right_padding	10
bspc config left_padding	10
bspc config bottom_padding	10
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a qutebrowser desktop='^2'
bspc rule -a Zathura state=tiled
bspc rule -a discord desktop='^9'
bspc rule -a Signal\ Beta desktop='^10'
bspc rule -a whatsapp-nativefier-d40211 desktop='^10'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
