#! /bin/sh

my_laptop_external_monitor=$(xrandr --query | grep 'HDMI1')
if [[ $my_laptop_external_monitor = *\ connected* ]]; then
    xrandr --output HDMI1 --mode 1920x1080 --rate 74.97 --above eDP1 --noprimary
else
    xrandr --output HDMI1 --off
fi

# Background
feh --bg-scale $HOME/pictures/wallpapers/dan-otis-OYFHT4X5isg-unsplash.jpg &

# Trackpad config
xinput set-prop "DELL0B26:00 04F3:3147 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "DELL0B26:00 04F3:3147 Touchpad" "libinput Natural Scrolling Enabled" 1

# Compositor
picom &

# Notification
killall dunst
dunst &

# Keybindings and keyboard
setxkbmap br -variant abnt2 &
xsetroot -cursor-name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $my_laptop_external_monitor = *\ connected* ]]; then
  echo "-------------------"
  bspc monitor eDP1 -d I II III IV V
  bspc monitor HDMI1 -d VI VII VIII IX X
  bspc wm --reorder-monitors HDMI1 eDP1
else
  echo "|||||||||||||||||"
  bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
fi

# Polybar
$HOME/.config/polybar/launch.sh &


bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         42

bspc config normal_border_color   '#4b565c'
bspc config focused_border_color  '#d3c6aa'

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a yad-calendar state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a zoom state=floating center=on follow=on border=off desktop=^6
